export const STR = {
  title: "Food Bank Manager",
  subtitle: "Feed your community, one meal at a time",
  startDay: "Start Day",
  nextDay: "Next Day",
  gameOver: "Game Over",
  restart: "Play Again",
  day: "Day",
  score: "Score",
  served: "Served",
  unsatisfied: "Unsatisfied",
  peopleFed: "People Fed",
  foodWasted: "Food Wasted",
  reputation: "Reputation",
  inventory: "Inventory",
  client: "Client",
  serve: "Serve",
  skip: "Skip",
  need: "Needs",
  satisfied: "Satisfied!",
  unhappy: "Left unsatisfied",
  donation: "Donation arrives!",
  phaseMorning: "Morning — Donations",
  phaseService: "Service — Help clients!",
  phaseNight: "End of Day",
  upgrade: "Upgrade",
  upgradeTitle: "Upgrade Your Food Bank",
  shelfSpace: "Shelf Space",
  fridge: "Refrigeration",
  volunteers: "Volunteers",
  shelfSpaceDesc: "Store more food",
  fridgeDesc: "Food lasts longer",
  volunteersDesc: "Serve faster",
  level: "Lvl",
  cost: "Cost",
  buy: "Buy",
  outOfStock: "Out of stock!",
  patience: "Patience",
  largeFamily: "Large Family",
  restriction: "Restriction",
  noDairy: "No dairy",
  noGluten: "No gluten",
  noMeat: "No meat",
  dayComplete: "Day Complete!",
  yourScore: "Your Score",
  highScore: "High Score",
  newHighScore: "New High Score!",
  tapToServe: "Tap a client, then tap food to give",
  controls: "Click client → Click food → Click Serve",
  gameGoal: "Feed as many people as you can. Don't let 3 leave hungry in a row.",
  shift: "Shift",
  foodBank: "Food Bank",
  community: "Community",
  fed: "fed",
  hungry: "hungry",
  spoilage: "Spoiled",
  saved: "Saved",
  continue_: "Continue",
};

